---
title: "charity data"
author: "Marina Vabistsevits"
date: "2022-08-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(vroom)
library(dplyr)
library(lubridate)
library(ggplot2)
library(cowplot)
library(tidyr)
library(sf)
source("functions.R")
options(scipen = 9)
```

```{r}
# testing working with OS POI data ----- !!!!! this data is not publicly available, so no data/results will be shared (this is for testing/ proof of principle / comparison with OSM data only)
all_poi <- readr::read_delim("data/raw/Download_retail_poi_england_rectangle_2046746/poi_4621139/poi-extract-2022_03.csv", delim="|")
allcharity <- all_poi %>%  filter(pointx_class == '09480714') 
allcharity %>% count(name) %>% View()

allcharity_w_loc %>% filter(is.na(ladnm)) %>% View()

# add long lat to charity shops
dat_pst <- allcharity_w_loc %>% select(pcds) %>%distinct() 
tmp<- data_frame() #### takes > 5 mins
for (i in 1:nrow(dat_pst)){
  out<- PostcodesioR::postcode_lookup(dat_pst$pcds[i]) %>% select(postcode,longitude ,latitude, country, 
                                                    lsoa11nm = lsoa, lsoa11cd=lsoa_code, 
                                                    msoa11nm = msoa, msoa11cd=msoa_code,  
                                                    ladnm = admin_district, ladcd=lau2_code )
  tmp <- bind_rows(tmp,out)
}
dat_pst<- left_join(dat_pst, tmp, by = c("pcds" = "postcode" )) %>% distinct() # 6710

allcharity_w_loc<- left_join(allcharity_w_loc, dat_pst, by ="pcds") %>% filter(country == "England") # 7549
dim(allcharity_w_loc)

write.csv(allcharity_w_loc, "data/processed/charity_shops_OS_w_loc.csv")

allcharity_w_loc_OS <- read.csv("data/processed/charity_shops_OS_w_loc.csv")
allcharity_w_loc_OS %>% count(ladnm) %>% View()
```


```{r}
# merge meta with charity

charity<- read.csv("data/processed/charity_shops_OS_w_loc.csv") %>% 
  select(name, latitude, longitude, lsoa11nm, msoa11nm, postcode=pcds)

tidy_lsoa<-read.csv("data/processed/tidy_lsoa_with_ladnm_r2.csv") 

area_merged<- left_join(charity , 
                        tidy_lsoa %>% select(-latitude, -longitude))

write.csv(area_merged, "data/processed/charity_shops_OS_w_loc_w_area_ratings.csv")
area_merged<- read.csv("data/processed/charity_shops_OS_w_loc_w_area_ratings.csv")


#generation test data for areas
area_merged %>% filter(grepl("Bristol", lsoa11nm)) %>% 
  write.csv("data/processed/charity_shops_OS_w_loc_w_area_ratings_Bristol.csv")

area_merged %>% filter(grepl("Leeds", lsoa11nm)) %>% 
  write.csv("data/processed/charity_shops_OS_w_loc_w_area_ratings_Leeds.csv")

```




```{r}
# OSM data -- queried in python scriopt ...
dat <- vroom("data/raw/charity_coords_OSM_raw.csv") %>% select(index, name, latitude = lat, longitude = lon) %>% mutate(row = row_number())
dat_geo <- data_frame()

for (i in 1:nrow(dat)){
  print(i)
  out <- PostcodesioR::reverse_geocoding(longitude = dat$longitude[i], latitude = dat$latitude[i], limit =1)
  if (!is.null(out)){
    out <- out %>% 
      unlist() %>% as.matrix() %>% t() %>% as.data.frame() %>% 
      select(postcode, lsoa11nm = lsoa, msoa11nm = msoa, lsoa11cd = codes.lsoa, msoa11cd = codes.msoa) %>% mutate(row = i)
    dat_geo <- bind_rows(dat_geo, out)
  }
}

dat2 <- left_join(dat, dat_geo, by = "row")
# fix unmapped corrds manually
dat2_sub <- dat2 %>% filter(is.na(postcode)) %>%  select(index:postcode)
#write.csv(dat2_sub, "data/processed/tmp_missing_postcode2.csv")
dat2_sub <- read.csv("data/processed/tmp_missing_postcode_manual_add.csv") %>% filter(!is.na(postcode)) %>% select(-latitude, -longitude)
tmp<- data_frame() 
for (i in 1:nrow(dat2_sub)){
  out<- PostcodesioR::postcode_lookup(dat2_sub$postcode[i]) %>% select(postcode,longitude ,latitude, 
                                                    lsoa11nm = lsoa, lsoa11cd=lsoa_code, 
                                                    msoa11nm = msoa, msoa11cd=msoa_code )
  tmp <- bind_rows(tmp,out)
}
dat2_sub<- left_join(dat2_sub, tmp, by = c("postcode" )) %>% distinct() 
charityOSM <- dat2 %>% filter(!is.na(postcode)) %>% bind_rows(dat2_sub) %>% distinct()

vroom_write(charityOSM, "data/processed/charity_shops_OSM_coords_w_postcode.csv")


tidy_lsoa<-read.csv("data/processed/tidy_lsoa_with_ladnm_r2.csv") 
area_mergedOSM<- left_join(charityOSM , 
                        tidy_lsoa %>% select(-latitude, -longitude))

write.csv(area_mergedOSM, "data/processed/charity_shops_OSM_w_loc_w_area_ratings.csv")
area_mergedOSM<- vroom("data/processed/charity_shops_OSM_w_loc_w_area_ratings.csv")

# get charity shops by area
msoa_counts <- charityOSM %>% count(msoa11nm) 
msoa_counts$ladnm <- stringr::str_sub(msoa_counts$msoa11nm, end=-5)
counts_by_ladnn <- msoa_counts %>% group_by(ladnm) %>% summarise(total=sum(n))




#generation test data for areas
area_mergedOSM  %>% filter(grepl("Bristol", lsoa11nm)) %>% 
  write.csv("data/processed/charity_shops_OSM_w_loc_w_area_ratings_Bristol.csv")

area_mergedOSM  %>% filter(grepl("Leeds", lsoa11nm)) %>% 
  write.csv("data/processed/charity_shops_OSM_w_loc_w_area_ratings_Leeds.csv")

area_mergedOSM  %>% filter(grepl("Southampton", lsoa11nm)) %>% 
  write.csv("data/processed/charity_shops_OSM_w_loc_w_area_ratings_Southampton.csv")

area_mergedOSM  %>% filter(grepl("Brighton and Hove", lsoa11nm)) %>% 
  write.csv("data/processed/charity_shops_OSM_w_loc_w_area_ratings_Brighton.csv")

area_mergedOSM  %>% filter(grepl("Warwick", lsoa11nm)) %>% 
  write.csv("data/processed/charity_shops_OSM_w_loc_w_area_ratings_Warwick.csv")

area_mergedOSM  %>% filter(grepl("Newcastle upon Tyne", lsoa11nm)) %>% 
  write.csv("data/processed/charity_shops_OSM_w_loc_w_area_ratings_Newcastle.csv")

area_mergedOSM  %>% filter(grepl("York", lsoa11nm)) %>% 
  write.csv("data/processed/charity_shops_OSM_w_loc_w_area_ratings_York.csv")

area_mergedOSM  %>% filter(grepl("Cheltenham", lsoa11nm)) %>% 
  write.csv("data/processed/charity_shops_OSM_w_loc_w_area_ratings_Cheltenham.csv")


area_mergedOSM  %>% filter(grepl("Cambridge", lsoa11nm)) %>% 
  write.csv("data/processed/charity_shops_OSM_w_loc_w_area_ratings_Cambridge.csv")

```


```{r}
# compare shops per area OS vs OSM
os_vs_osm <- full_join(
  area_merged %>% 
    count(ladnm) %>% rename(os_n=n) %>% 
    mutate(ladnm = gsub(", City of", "", ladnm)) %>% 
    mutate(ladnm = gsub(", County of", "", ladnm)),
  counts_by_ladnn %>% 
    rename(osm_n = total)) %>% 
  
  replace(is.na(.), 0) %>% 
  mutate(pct_missing = round(1 - (osm_n/os_n),2)) %>% 
  mutate(pct_missing = ifelse(pct_missing <0 , 0, pct_missing))

write.csv(os_vs_osm, "data/processed/charity_shops_comparison_OS_vs_OSM.csv")
os_vs_osm <- read.csv("data/processed/charity_shops_comparison_OS_vs_OSM.csv")

hist(os_vs_osm$pct_missing)
mean(os_vs_osm$pct_missing) #0.65

```

